name: CI Fundamentals

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Display project files
        run: ls -la

      - name: Display application files
        run: ls -la app

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t devsecops-flask-app:ci ./app

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: devsecops-flask-app:ci
          format: table
          scanners: vuln
          severity: HIGH,CRITICAL
          exit-code: '1'

      - name: Show pipeline message
        run: echo "DevSecOps pipeline is running"
